# Generated by Django 3.0.4 on 2020-03-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
